version: '3'
services:
  dmg-tracking:
    image: docker.synchrotron.org.au/dmg/dmg-tracking:latest
    restart: always
    environment:
     - TZ=Australia/Melbourne
     - MONGODB_HOST=mongo
     - MONGODB_PORT=27017
     - PORTAL_HOST=${PORTAL_HOST}
     - PORTAL_CLIENT=${PORTAL_CLIENT}
     - PORTAL_PASSWORD=${PORTAL_PASSWORD}
    ports:
     - "5000:5000"
    depends_on:
     - mongo
  mongo:
    image: "mongo:latest"
    restart: always
    volumes:
     - data-volume:/data/db
volumes:
  data-volume:
